version: '3.7'
services:
  postgres:
    container_name: pg_test
    image: postgres:10.5
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: '3'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - '5438:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/test.sql:/docker-entrypoint-initdb.d/test.sql
